project:
  type: website
  output-dir: docs

website:
  title: "ZS"
  navbar:
    logo: assets/zs-logo.svg
    right:
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - posts.qmd
      

format:
  html:
    theme:
      light: [united, styles.scss]
    toc: false

editor: visual