project:
  type: website
  output-dir: docs
  resources:
    - google4b13fe5c076ff8e0.html
website:
  title: "ZS"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - posts.qmd
      
format:
  html:
    theme:
      light: [united, styles.scss]
    toc: false
editor: visual